### ISSUE TITLE
Name collision on `Scheduler` when `import org.atnos.eff._` + Monix

### ISSUE THREAD

**Issue by benhutchison** [atnos-org/eff#106]
Raising this as a discussion - there's not a clear cut solution.

`monix.execution.Scheduler` is a core abstraction in Monix that you find yourself passing around.

Generally I tend to use wildcard imports of Eff because I use Eff heavily and like to get early warning if there's clashes with other libraries I commonly use. I noticed that recently, the Eff package has added [Scheduler](https://github.com/atnos-org/eff/blame/master/shared/src/main/scala/org/atnos/eff/Scheduler.scala) which collides with Monix.

Eff's own `Scheduler` type is pretty young, I wonder if there's scope to migrate it to a less collision-prone name?

**Comment by etorreborre** [comment]
Yes, we can either change the name of move it to another package like `org.atnos.eff.concurrent`.

**Comment by etorreborre** [comment]
Fixed with #108

**Comment by benhutchison** [comment]
thanks for quick but good solution @etorreborre

**Comment by etorreborre** [comment]
I will publish `4.4.0` in the next days with that change.
