### ISSUE TITLE
Who "invented" Eff? Gordon Plotkin and Matija Pretnar afaict...

### ISSUE THREAD

**Issue by benhutchison** [atnos-org/eff#111]
The introduction to this library might lead people into thinking that Kiselyov etc "invented" Eff, as it did me for a long time. In fact there was an explosion of different implementations of algebraic effects in the 2011 to 2013 timescale. But in my opinion, some credit for Eff should be attributed to Gordon Plotkin and Matija Pretnar whose theoretical work seems to have enabled them all.

**Comment by etorreborre** [comment]
Oleg has a good presentation on some foundational work on effects: https://www.youtube.com/watch?v=GhERMBT7u4w. He relates in big part extensible effects to Cartwright and Felleisen's "Extensible Denotational Language Specifications".

**Comment by etorreborre** [comment]
PS: when/how should I consider that this issue is closed :-)?

**Comment by benhutchison** [comment]
The bit that seems incomplete in that account is that "Extensible Denotational Language Specifications" came out in 1994. Evidently it wasn't "done and dusted" then because it took nearly two decades for implementations to appear.

But in the 2011-2013 period, the Haskell [Eff library](https://hackage.haskell.org/package/extensible-effects-1.0), Edwin Brady's [Idris Effect library](https://eb.host.cs.st-andrews.ac.uk/drafts/effects.pdf) and Matija Pretnar's [eff language](https://github.com/matijapretnar/eff/commit/11f2c2e44f6f3f544c694c38cd2e651fbcf56e23) all emerged with similar designs, having been developed more or less concurrently. What was the event that inspired all these to co-occur? 

It seems to me that Matija Pretnar's phd research, supervised by Gordon Plotkin, played a significant role, perhaps worth crediting.

Agree Im misusing an issue to have a conversation. I should probably send a README PR mentioning some of these other predecessors in the Eff space, but Ive already promised to do the docs re-org next so it'll have to get in the queue.

**Comment by etorreborre** [comment]
You're right, there might be two different things here:

 - the idea of effect handling for interpreting programs
 - the support of typechecked effect handling in programming languages and / or libraries
