### ISSUE TITLE
Please republish site

### ISSUE THREAD

**Issue by benhutchison** [atnos-org/eff#128]
I noticed that the [Task docs I added to the main effects menu](https://github.com/atnos-org/eff/blob/master/src/test/scala/org/atnos/site/OutOfTheBox.scala#L23) dont appear for me at http://atnos-org.github.io/eff/org.atnos.site.OutOfTheBox.html

Has the site just not been republished?

**Comment by etorreborre** [comment]
Done (and I released a final 5.0.0 version)
