### ISSUE TITLE
Documentation: "no file found at" instead of sample code in the tutorial

### ISSUE THREAD

**Issue by jmhofer** [atnos-org/eff#129]
In the [tutorial](http://atnos-org.github.io/eff/org.atnos.site.Tutorial.html), there are a lot of places with "no file found at..." instead of sample code blocks, for example `no file found at ../jvm/src/test/scala/org/atnos/site/snippets` in the "Create an ADT representing your grammar" section.

**Comment by etorreborre** [comment]
Thanks for warning me. This should be ok now: [Tutorial](http://atnos-org.github.io/eff/org.atnos.site.Tutorial).

**Comment by jmhofer** [comment]
This link works. - But the link in the Documentation and in the README (the same link I gave above, which has an additional `.html`) don't seem to work at all anymore now?

**Comment by etorreborre** [comment]
It works now: http://atnos-org.github.io/eff/org.atnos.site.Tutorial.html. The puzzling thing is that it was not working for a while after I deployed, only the page without .html was working.
