### ISSUE TITLE
How to use catchLeft?

### ISSUE THREAD

**Issue by vivekkpai** [atnos-org/eff#142]
Hi,

I have a number of DSLs (which were written using Eff) that all _translate_ to _throwableEither. All of the translation happens during interpretation - the DSLs themselves do not have any dependency on _throwableEither only their interpreters do.

I want to provide a way for _users_ of the DSLs to handle lefts. However, catchLeft doesn't help capturing this. Is there some way to do this without changing the DSLs? It is okay for DSL users to explicitly specify requirement of _ThrowableEither in the effect stack.

Apologies if I am not following protocol its my first post here. Also, I am very new to Eff and Scala.

-vivek

**Comment by benhutchison** [comment]
Hi vivek, the best place for "How do I do X with Eff?" is the gitter channel https://gitter.im/atnos-org/eff

I can't usefully comment on your problem without seeing some example code (even an incomplete sketch helps), I dont understand the DSLs well enough from this abstract description.

**Comment by etorreborre** [comment]
@vivekkpai I am closing this issue here, please continue the discussion on gitter.
