### ISSUE TITLE
How to use fs2.Stream compile for Eff[R, ?] ?

### ISSUE THREAD

**Issue by vitold** [atnos-org/eff#162]
Hi Eric, 

I'm currently puzzled a bit with understanding the proper usage of both Eff and fs2.Stream API. 

What I want to do (let's assume some synthetic situation):

```scala
def getEffects[S: _io : _option]: Eff[S, Int] = Eff.pure(1)
type Stack = Fx2[IO, Option]
Stream.eval(getEffect[Stack])
        .compile
        .toList
        .runOption
        .unsafeRunSync
```
and apparently it fails with
```scala
could not find implicit value for parameter compiler: fs2.Stream.Compiler[[x]org.atnos.eff.Eff[Stack,x],G]
[error]     val res: Eff[Stack, List[Int]] = Stream.eval(getEffect[Stack]).compile.toList
```
According to fs2 documentation, adding the instance of cats.effect.Effect helps, but i have a problem with writing the actual implementation of some functions:
```scala
    implicit def effectEff[R]: cats.effect.Effect[Eff[R, ?]] = new cats.effect.Effect[Eff[R, ?]] {
      override def runAsync[A](fa: Eff[R, A])(cb: Either[Throwable, A] => IO[Unit]): SyncIO[Unit] = ???

      override def async[A](k: (Either[Throwable, A] => Unit) => Unit): Eff[R, A] = ???

      override def asyncF[A](k: (Either[Throwable, A] => Unit) => Eff[R, Unit]): Eff[R, A] = ???

      override def suspend[A](thunk: => Eff[R, A]): Eff[R, A] = {
        fromIO(IO(thunk)).flatten
      }

      override def bracketCase[A, B](acquire: Eff[R, A])(use: A => Eff[R, B])(release: (A, ExitCase[Throwable]) => Eff[R, Unit]): Eff[R, B] = {
        Eff.bracketLast(acquire)(use)(a => release(a, ExitCase.complete[Throwable]))
      }

      override def flatMap[A, B](fa: Eff[R, A])(f: A => Eff[R, B]): Eff[R, B] = fa.flatMap(f)

      override def tailRecM[A, B](a: A)(f: A => Eff[R, Either[A, B]]): Eff[R, B] =
        Eff.EffMonad[R].tailRecM(a)(f)

      override def raiseError[A](e: Throwable): Eff[R, A] = ???

      override def handleErrorWith[A](fa: Eff[R, A])(f: Throwable => Eff[R, A]): Eff[R, A] =
        ioAttempt(fa).flatMap {
          case Left(t) => f(t)
          case Right(a) => Eff.pure(a)
        }

      override def pure[A](x: A): Eff[R, A] = Eff.pure(x)
    }
```
Looking into the type signatures now I'm wondering does it even make any sense?

**Comment by benhutchison** [comment]
See also: https://github.com/atnos-org/eff/pull/148#issuecomment-413078890

I dont see how a generalized Eff[R, A] can be a Cats' Effect or friends (a
simpler concept), the only way it could work is when there's a known set of
effects in stack R that can be mapped onto Cats' Effect.

I think the way to interop Eff with FS2 is to interpret your Eff program
down into a Cats Effect on every element of the stream, ie the Eff
interpretation is inside Stream.eval() in your example above. Does that
make sense?

**Comment by vitold** [comment]
@benhutchison Thanks for the link to the previous discussion. It clarifies the situation.

**Comment by etorreborre** [comment]
The funny thing is that "streaming" can also been seen as an effect after all. So you would think that you could have some computation `Eff[S, A]` that once interpreted can yield many `A`s but also `List[Option[A]]` or `Option[List[Future[A]]]` or `Future[Option[List[A]]]` depending on the interpreters and the order in which you run them. Unfortunately this story becomes quite hard to implement once you want good concurrency, good general performance and resources management.
