### ISSUE TITLE
2.13 support ?

### ISSUE THREAD

**Issue by smarter** [atnos-org/eff#185]
It appears that eff hasn't been published for 2.13 yet, is this planned ?

**Comment by symbiont-eric-torreborre** [comment]
@benhutchison is the boss now :-).

**Comment by benhutchison** [comment]
I'll get into that.

**Comment by benhutchison** [comment]
Current dependency issues:

unresolved dependency: io.monix#monix_2.13;3.0.0-RC3: not found
unresolved dependency: com.twitter#util-collection_2.13;19.1.0: not found
unresolved dependency: io.catbird#catbird-util_2.13;19.8.0: not found

@smarter Do you have an urgent need (if so, please describe) or happy to wait for the above to move?

**Comment by smarter** [comment]
Not urgent ([I just had to disable an integration test in dotty](https://github.com/lampepfl/dotty/pull/7019/commits/be5faf169d8e4ecd2b8f3def14d99aab68335e9c)), I'm fine with waiting :).

**Comment by benhutchison** [comment]
Upstream issues to track
https://github.com/monix/monix/issues/862
https://github.com/travisbrown/catbird/issues/145

**Comment by alexandru** [comment]
We are blocked by Cats-Effect 2.0 atm. We're waiting for the final release. Should happen any day now.

**Comment by alexandru** [comment]
Monix `3.0.0` is now released with support for Scala 2.13

**Comment by alexandru** [comment]
Sorry it took so long, we we're blocked by upstream dependencies as well.

**Comment by xuwei-k** [comment]
https://github.com/atnos-org/eff/pull/191 😃

**Comment by BenHutchisonSeek** [comment]
2.13 is now supported for all modules except Twitter integration in the 5.5.1 release

**Comment by takayahilton** [comment]
Done in https://github.com/atnos-org/eff/pull/193.

**Comment by benhutchison** [comment]
published in v5.5.2
