### ISSUE TITLE
Future maintenance of Eff AddOns (Twitter, Scalaz, Monix, Doobie)

### ISSUE THREAD

**Issue by benhutchison** [atnos-org/eff#186]
This issue is to track a decision process around how to support several Eff integration AddOns:
- [Twitter](https://github.com/atnos-org/eff/tree/master/twitter/src/main/scala/org/atnos/eff/addon/twitter)
- [Monix](https://github.com/atnos-org/eff/tree/master/monix/shared/src/main/scala/org/atnos/eff/addon/monix)
- [Scalaz](https://github.com/atnos-org/eff/tree/master/scalaz/src/main/scala/org/atnos/eff/addon/scalaz)
- [Doobie](https://github.com/atnos-org/eff/tree/master/doobie/src/main/scala/org/atnos/eff/addon/doobie)

I'm in the process of taking over maintenance of Eff from @etorreborre (who is mainly working in Haskell these days) and want to ensure I keep the maintenance load at a level I can sustain. 

AddOns add extra maintenance because they require me to have knowledge of the external library, but most of all because they couple Eff's releases to external processes (eg #185 ).

If you use one of the above AddOns, please let me know with a comment on this issue. (I dont personally use any of them.)

To signal my intentions, I will continue to support AddOns that are actively used, but may over time divest them into separate GitHub projects, co-owned with their users. AddOns without users will be deprecated.

**Comment by ben-healthforge** [comment]
Twitter (not currently but have in the past and likely to in the future).  Might make sense for it to become a sub-project of [catbird](https://github.com/travisbrown/catbird)?

**Comment by xuwei-k** [comment]
I'm using eff-monix addon in production.

**Comment by benhutchison** [comment]
@yutachaos & @dispalt, can I just clarify are you using _both_ scalaz and monix addons, or just one of them?

**Comment by dispalt** [comment]
Oh sorry it looks like the comment was edited, I use monix only.

**Comment by BenHutchisonSeek** [comment]
Thanks all for feedback. Summarizing my thinking:

- Monix support seems to be the greatest value - definitely continue that.
- Scalaz has a current user & contributor, so it will be supported

Im thinking about deprecating the Twitter and Doobie integrations. 

@ben-healthforge happy to collaborate on splitting Twitter support into a separate repo if that's something your willing to co-maintain?

**Comment by benhutchison** [comment]
All 4 addons are available for Scala 2.13 in v5.5.2
