### ISSUE TITLE
Use scala-steward?

### ISSUE THREAD

**Issue by takayahilton** [atnos-org/eff#199]
**Description**
>Scala Steward is a robot that helps you keeping library dependencies and sbt plugins up-to-date.

https://github.com/fthomas/scala-steward

All you have to do is edit this [repos](https://github.com/scala-steward-org/repos/edit/master/repos.md) and send PR.

**Comment by benhutchison** [comment]
https://github.com/scala-steward-org/repos/pull/34

**Comment by takayahilton** [comment]
Thanks!
