### ISSUE TITLE
missing 5.7.0 tag on GitHub

### ISSUE THREAD

**Issue by xuwei-k** [atnos-org/eff#238]
https://repo1.maven.org/maven2/org/atnos/eff_2.13/

![maven](https://user-images.githubusercontent.com/389787/75321473-34b73180-58b4-11ea-997e-a91771d7af15.png)

<hr />

https://github.com/atnos-org/eff/tags

![github](https://user-images.githubusercontent.com/389787/75321477-3680f500-58b4-11ea-88f3-e31c79582f8c.png)

**Comment by benhutchison** [comment]
Ive add the tag, pls reopen if something else needed
