### ISSUE TITLE
Scalajs 1.x support

### ISSUE THREAD

**Issue by benhutchison** [atnos-org/eff#245]
I'm interested to hear if anyone using Eff is wanting Scalajs 1.x support?

I added Scalajs to Eff several years ago as I was using it then, but I dont anticipate using Eff&Scalajs in future. So I'm interested to identify if there's an actual user needing this before publishing.

**Comment by xuwei-k** [comment]
- https://repo1.maven.org/maven2/org/atnos/eff_sjs1_2.13/
- https://repo1.maven.org/maven2/org/atnos/eff_sjs1_2.12/
