### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by xuwei-k** [atnos-org/eff#259]
There are some updates since latest release 🙏 
https://github.com/atnos-org/eff/compare/v5.7.0...master

**Comment by BenHutchisonSeek** [comment]
Acknowledged. I'll do this one, but lets also try to ensure you have the ability to do a release. 

[Here](https://issues.sonatype.org/browse/OSSRH-21591?focusedCommentId=792285&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-792285) is where I got @etorreborre to authorise me to do releases to sonatype

**Comment by xuwei-k** [comment]
@etorreborre 🙏 
https://issues.sonatype.org/browse/OSSRH-21591?focusedCommentId=926652&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-926652

**Comment by etorreborre** [comment]
I added a comment on the sonatype issue.

**Comment by xuwei-k** [comment]
Thanks!

**Comment by xuwei-k** [comment]
- https://github.com/atnos-org/eff/releases/tag/5.8.0
- https://repo1.maven.org/maven2/org/atnos/eff_2.13/5.8.0/
