### ISSUE TITLE
Cats Effect 3 migration

### ISSUE THREAD

**Issue by kubukoz** [atnos-org/eff#330]
Hi! Are there any plans in place to migrate to Cats Effect 3? It would be good to see if there are any blockers before the RCs are released. https://github.com/typelevel/cats-effect/issues/1330

**Comment by benhutchison** [comment]
I have no plans. Im not sure if the cats effect integration has any active users actually. @xuwei-k you were using Eff with Scalaz right?

**Comment by xuwei-k** [comment]
https://github.com/atnos-org/eff/commit/5323ac8acf91597ed3756a78b133ccd9f8066fe0
