### ISSUE TITLE
Widening the effects a computation

### ISSUE THREAD

**Issue by mikesperber** [atnos-org/eff#345]
I'm banging my head against writing a function like this:

```scala
  def foo[R](effects: Eff[R, Unit]): Eff[Fx.append[Fx.fx1[State[Int, *]], R], Unit] =
    effects
```
I.e. I have a computation `effects`, and I want to embed it in a computation that has one or several additional effects - I can't figure out how to do it. (Polysemy has a `raise` function to do this.)

It would be even better if I could express the relationship more indirectly, like so:

```scala
  def foo1[U](implicit m: State[Int, *] <= U): Eff[m.Out, Unit] => Eff[U, Unit] = { effects =>
    m.inject(effects)
  }
```

But `inject` is the wrong thing here - is there a right thing?

(I just started using `eff`, which is GREAT - many thanks!)

**Comment by benhutchison** [comment]
You can see a working example on this page to try copy/modify https://atnos-org.github.io/eff/org.atnos.site.Cookbook.html#partial-interpretation

`repeatM(times, incrementCounter[Fx.prepend[StateInt, R]])`

Adding effects is definitely a common thing to do in Eff.

**Comment by mikesperber** [comment]
Thanks for the quick reply!

I haven't been able to make the Cookbook example work, as `effects` is passed in - I don't have control over its effects. Naively translated, the Cookbook example would look like this:

```scala
  def foo[R](effects: Eff[R, Unit]): Eff[Fx.prepend[State[Int, *], R], Unit] =
    effects[Fx.prepend[State[Int, *], R]]
```

But that (of course) doesn't typecheck.

I.e. I know how I can control the effect *type* - but I need to manipulate the *value* to match the extended effect row.

**Comment by benhutchison** [comment]
Mike, the only guidance I can give may be a bit unhelpful: something in
your description seems a bit off, in that the thing you're trying to do
just shouldnt be required to use Eff.

Any effect you need to be available, declare as a constraint in the method
where you use it (eg incrementNTimes[R :_err :_log]has 2 constraints_err &
_log]). Whoever calls that method either has the same constraint declared,
or else they must introduce the effect via eg prepend as per the cookbook
example. You shouldnt need a situation where the returned value from a
method has more effects than the one passed in.

So with your foo example, declare a State constraint on foo, and the caller
can prepend a state effect to satisfy it.

**Comment by mikesperber** [comment]
Thanks for your patience with this - and again the quick response.

I agree there's a mismatch between what I'm trying to do and how Eff operates. But I'd argue that what I'm trying to do is necessary for modular software construction with effects:

One part of the program supplies a bunch of effectful values, that happen to sit in a data structure. I'd like to compose those with some other effects in another part of the program. I can't easily go back and tell the first to widen its effects. It also seems counterintuitive that I can't embed an effectful value into a computation that has strictly more effects.

(The oncrete example is a card game, where the player strategies are represented as effectful computations, and the strategies are sitting in a map. Now I'd like to embed the players into the overall game. But most effect examples I've written involve something similar.)

**Comment by benhutchison** [comment]
If you have two modules that use different effects, that's a vanilla easy
case. Whatever top method calls the two modules needs to declare the union
of the effects declared in each module. That's all, nothing else needed.

**Comment by etorreborre** [comment]
@mikesperber I've been away from `eff` for some time but the `into` method should work:
```
  def foo[R](effects: Eff[R, Unit]): Eff[Fx.prepend[State[Int, *], R], Unit] =
    effects.into[Fx.prepend[State[Int, *], R]]
```

This effectively transform the data structure used to store effects into the new "shape" given by `Fx.prepend[State[Int, *], R]`. Note that this is all quite complex internally because we encode effects types as a tree for performance reasons at compile time. It would be worth revisiting that choice with Scala3 where type-level programming might be more performant.

**Comment by mikesperber** [comment]
Both your approaches work, @benhutchison & @etorreborre. Many, many thanks for your help!

**Comment by benhutchison** [comment]
Hi Eric, good to hear from you :)

I'd be interested to hear your thoughts on what use cases `into` is most
suited to.

**Comment by etorreborre** [comment]
I don't remember when / if I had to use `.into`. The mechanism is involved in a few interpreters like `translateInto` so I might have surfaced it for that reason. It is also used in a few tests in the project like `EffSpec`, `SubscribeEffect` or the `EffMacroSpec`.
