### ISSUE TITLE
Twitter util Future for Async

### ISSUE THREAD

**Issue by akozhemiakin** [atnos-org/eff#37]
Along with Scala Future, Scalaz Task and Monix Task I think it would be useful to provide integration (Async effect) with twitter util future. I've just started playing with Eff and I believe that I do not have enough expertise with Eff to implement it myself correctly  (at least right now and fast :) ) But I'm ready to take a shot if no one will pick this up in the near future.

**Comment by etorreborre** [comment]
We could add another module, looking like `eff-scalaz` or `eff-monix` and implement the `Async` effect a bit like the `AsyncFutureInterpreter` is implemented.
