### ISSUE TITLE
Provide and document easy to have shorter method signatures 

### ISSUE THREAD

**Issue by boggle** [atnos-org/eff#56]
Hi,

I've recently been starting to use eff. And it's amazing, thanks for building this!

However what keeps bugging me is that it leads to fairly long method signatures for monad stacks with many effects

```
def foo[R : _foo : _bar : _baz : ...](myArg: MyInputType): MyOutputType
```

Is there an established best practice for defining aliases for long chains of effect context bounds? If so, could you please add that to the documentation?

Thanks!

**Comment by etorreborre** [comment]
I proposed [this](https://github.com/atnos-org/eff/issues/39#issuecomment-271163511) but there is no established practice for now.

**Comment by edmundnoble** [comment]
@etorreborre Perhaps we should provide extensible coproducts of `Member` objects? Then it might look more like:
```scala
type _stack = _foo +: _bar +: MemberNil
```
and the projection functions would be implicit.

**Comment by etorreborre** [comment]
It would be more like a HList of implicit member instances, wouldn't it? Yes it's worth investigating if a bunch of implicit definitions to create that HList when the members are in scope, then extract them when needed individually.

**Comment by edmundnoble** [comment]
Yeah, more like an HList. I'll give it a try, but it might end up hitting the implicit inference limits.

**Comment by etorreborre** [comment]
Yes that wouldn't be surprising.

**Comment by benhutchison** [comment]
Is there any further progress or thinking on this? Or did it tend intractable to get working? I too would like a way to alias multiple Members that commonly co-occur..

**Comment by etorreborre** [comment]
@benhutchison no work on that has been done yet. I would like to explore @edmundnoble's idea but I don't have time for this right now. Let me see if I can at least put this on my todo list.

**Comment by edmundnoble** [comment]
I think that this is actually possible in terms of implicit inference; I've heard success stories with using some kind of `ProductKK` to encode "bundled" instances, as well as using implicits to extract them.

**Comment by etorreborre** [comment]
I just wonder what's going to be the impact in terms of compilation times... Anyway, let's try.
