### ISSUE TITLE
Fx.append is not commputative

### ISSUE THREAD

**Issue by stephanh** [atnos-org/eff#71]
`type FMP = Fx.append[MP, Fx.fx2[Error, TimedFuture]]` works fine. However, if I do `type FMP = Fx.append[Fx.fx2[Error, TimedFuture], MP]` I get the following compiler error:

```
Cannot prove that org.atnos.eff.Eff[org.atnos.eff.FxAppend[org.atnos.eff.Fx1[org.atnos.eff.TimedFuture],org.atnos.eff.NoFx],scala.util.Either[Throwable,Option[A]]] =:= org.atnos.eff.Eff[org.atnos.eff.Fx.fx1[org.atnos.eff.TimedFuture],scala.util.Either[Throwable,Option[A]]].
[error]           .runAsync,
[error]            ^
```

**Comment by stephanh** [comment]
Please let me know if you need some reproducible code.

**Comment by etorreborre** [comment]
I need to make the definition of `runAsync` more generic. In the meantime you can get around this by writing
```scala
val e: Eff[FMP, Int] = ???

import org.atnos.eff.syntax.all._

e.runX.runX.runError.into[Fx1[TimedFuture]].runAsync
```

**Comment by stephanh** [comment]
I just used the version that worked, `type FMP = Fx.append[MP, Fx.fx2[Error, TimedFuture]]`.

**Comment by etorreborre** [comment]
Good. Anyway I am publishing the fix in `3.0.3-20170220075508-d419505` (available in a few minutes) if you want to test it.

**Comment by etorreborre** [comment]
It's available now.

**Comment by stephanh** [comment]
It worked. :+1:

**Comment by etorreborre** [comment]
Yay!
