### ISSUE TITLE
Value withFilter is not a member of Eff

### ISSUE THREAD

**Issue by anatoliykmetyuk** [atnos-org/eff#72]
Becasue `withFilter` is apparently not a member of `Eff`, you can not do pattern matching from the monadic flow syntax.

```scala
scala> import org.atnos.eff._
import org.atnos.eff._

scala> import org.atnos.eff.all._
import org.atnos.eff.all._

scala> import org.atnos.eff.syntax.all._
import org.atnos.eff.syntax.all._

scala> def f[R](x: (String, String)): Eff[R, String] = for { (a, b) <- pure(x) } yield a + b
<console>:23: error: value withFilter is not a member of org.atnos.eff.Eff[R,(String, String)]
       def f[R](x: (String, String)): Eff[R, String] = for { (a, b) <- pure(x) } yield a + b
                                                                           ^
<console>:23: error: type mismatch;
 found   : Any
 required: String
       def f[R](x: (String, String)): Eff[R, String] = for { (a, b) <- pure(x) } yield a + b

scala> def f[R](x: String): Eff[R, String] = for { a: String <- pure(x) } yield a
<console>:23: error: value withFilter is not a member of org.atnos.eff.Eff[R,String]
       def f[R](x: String): Eff[R, String] = for { a: String <- pure(x) } yield a
                                                                    ^

scala> def f[R](x: String): Eff[R, String] = for { a <- pure(x) } yield a
f: [R](x: String)org.atnos.eff.Eff[R,String]
```

**Comment by etorreborre** [comment]
I'm not a big fan (and neither is @edmundnoble) of adding an unsafe operation to the API. I think that `withFilter` is just creating bugs waiting to happen. You've never been bitten by that before?

**Comment by anatoliykmetyuk** [comment]
You mean that the pattern matching or explicit type specification happen on runtime? Probably this indeed decreases type safety. But on the other hand, syntax like `x._1` is ugly. Also case classes are nice to pattern match this way.

**Comment by etorreborre** [comment]
Yes your pattern matching is not checked by the compiler and will blow up at runtime.

**Comment by etorreborre** [comment]
Thanks for not insisting that we add such a feature, much appreciated :-)

**Comment by anatoliykmetyuk** [comment]
No problem, you have already been doing a pretty nice job with eff!

**Comment by benhutchison** [comment]
@anatoliykmetyuk I hit this problem myself. Theres some hints towards understand underlying problem and workaround syntax in the links off this stackoverflow: http://stackoverflow.com/questions/37982029/how-to-annotate-types-of-expressions-within-a-scala-for-expression/38018009#38018009
