### ISSUE TITLE
Traverse instance for Eff

### ISSUE THREAD

**Issue by edmundnoble** [atnos-org/eff#86]
I think we should be able to provide a `Traverse` instance for `Eff[S, A]`, given that all of the members of `S` have `Traverse` instances; by this I mean that all of them are possible to `run` without `detach`.

**Comment by etorreborre** [comment]
How would you write the type signature?
```scala
implicit def effTraverse[R : TraverseFx]: Traverse[Eff[R, ?]] = new Traverse[Eff[R, ?]] {
  def traverse[G[_]: Applicative, A, B](fa: Eff[R, A])(f: A => G[B]): G[Eff[R, B]] = ???
}

/**
 * can we get the Traverse instances for individual effects like that?
 */
trait TraverseFx[R <: Fx] {
  type H[_] <: Fx
  type T <: Fx

  def traverse: Traverse[H]
  def traverseFx: TraverseFx[T]
}
```

**Comment by etorreborre** [comment]
I'm closing this for now, please re-open if there is some interest again.
