### ISSUE TITLE
Compiler crashes 

### ISSUE THREAD

**Issue by wedens** [atnos-org/eff#94]
eff version: 4.3.0 (also tried on 4.2.0)
scala version: 2.12.1 (tried LBS and TLS, also 2.11.8)
http://scastie.org/30603
```scala
  sealed trait TestAlg[A]

  def interp[R, U, A](effect: Eff[R, A])(implicit m: Member.Aux[TestAlg, R, U], c: _task[U]): Eff[U, A] = ???

  type S = Fx.fx2[TimedTask, TestAlg]
  type R = Fx.fx1[TimedTask]

  def prg[R : _task](implicit R: TestAlg |= R): Eff[R, Int] = ???

  val x0: Eff[S, Int] = prg[S]
  interp(x0) // ok
  val x1: Eff[R, Int] = interp(x0) // compiler explosion
```
```
[error]   AdaptTypeError - foundType is Erroneous: org.atnos.eff.Member[Product with Serializable,org.atnos.eff.Fx2[Product with Serializable,Product with Serializable]]{type Out = org.atnos.eff.Fx1[<error>]}
```

**Comment by etorreborre** [comment]
@wedens this should actually be reported as a compiler bug :-(. In the meantime here is a workaround:
```scala
type S = Fx.fx2[TestAlg, TimedFuture]
type R = Fx.fx1[TimedFuture]
```

**Comment by wedens** [comment]
@etorreborre yeah, I agree that it should be. But I think we need to make some minimal case without eff. And I don't know eff internals good enough to do it.

The workaround is to use Future instead of Task?

**Comment by etorreborre** [comment]
No, sorry I just used `Future` because I didn't have the scalaz dependency :-). The workaround is to switch the types in the declaration of `S`.

**Comment by wedens** [comment]
https://github.com/scala/bug/issues/9960 can be relevant

**Comment by etorreborre** [comment]
Yes it definitely looks like the same.

**Comment by etorreborre** [comment]
I'm closing this because this is a Scala issue.
